[package]
name = "json_partitioned_example"
version = "0.1.0"
edition = "2024"

[dependencies]
joydb = { path = "../../joydb", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
