[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nutype = { path = "../toydb" }
serde = "*"
serde_json = "*"
uuid = { version = "1.3.3", features = ["v4"] }
