[package]
name = "test_suite"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
joydb = { path = "../joydb", features = ["json"]}
uuid = { version = "1.16.0", features = ["v4", "serde"] }
