[package]
name = "dummy"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toydb = { path = "../../toydb" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
